global:
  # Для тестирования используем smtp4dev или отключаем email
  smtp_smarthost: 'localhost:1025'  # smtp4dev для тестирования
  smtp_from: 'alertmanager@localhost'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      repeat_interval: 10m
    - match:
        service: kafka
      receiver: 'kafka-alerts'
    - match:
        service: application
      receiver: 'application-alerts'

receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://localhost:5001/'  # Для тестирования webhook
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/'
        send_resolved: true

  - name: 'kafka-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/'
        send_resolved: true

  - name: 'application-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/'
        send_resolved: true

# Для тестирования можно добавить email позже
#  - name: 'email-receiver'
#    email_configs:
#      - to: 'test@example.com'
#        from: 'alertmanager@localhost'
#        smarthost: 'localhost:1025'
#        subject: 'Alert: {{ .GroupLabels.alertname }}'
#        body: |
#          {{ range .Alerts }}
#          Alert: {{ .Labels.alertname }}
#          Instance: {{ .Labels.instance }}
#          Summary: {{ .Annotations.summary }}
#          Description: {{ .Annotations.description }}
#          Time: {{ .StartsAt }}
#          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']