server:
  port: 1111

spring:
  application:
    name: shop-stoplist-producer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/kafka_data
    username: kafka_user
    password: kafka_password