spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/kafka_data
    username: kafka_user
    password: kafka_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always

jpa:
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

sql:
  init:
    mode: always
    schema-locations: classpath:schema.sql
    data-locations: classpath:data.sql
    continue-on-error: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE